kind: Deployment
apiVersion: apps/v1
metatdata:
  name: webapp
spec:
  replicas:2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: abdul79/jenkins-ansible-project
          imagePullPolicy: Always
          ports:
            - containerPort: 80

