kind: Service
apiVersion: v1
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 8080
      targetport: 80
      nodePort: 31200
  selector:
    app: webappp
  type: Loadbalancer
